# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'ole-training' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ole-training
  pod 'AFNetworking'

  target 'ole-trainingTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ole-trainingUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
